name: Build and release

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build-release:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.x
      - name: set package.json version
        uses: menduz/oddish-action@master
        with:
          deterministic-snapshot: true
          only-update-versions: true
      - name: Install
        run: npm ci --legacy-peer-deps
      - name: Build static-local
        run: npm run build:static-local
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - name: Build for CDN
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - name: Move static-local into main build
        run: mv ./static-local ./build/static-local
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          cwd: './build'
          deterministic-snapshot: true
          registry-url: 'https://registry.npmjs.org'
          access: public
          gitlab-token: ${{ secrets.GITLAB_CDN_DEPLOYER_TOKEN }}
          gitlab-pipeline-url: ${{ secrets.GITLAB_CDN_DEPLOYER_URL }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
